# Generated by Django 5.2.8 on 2025-11-16 01:42

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('data_inizio', models.DateTimeField(help_text="Data e ora di inizio dell'evento.")),
                ('data_fine', models.DateTimeField(blank=True, help_text="Data e ora di fine dell'evento (opzionale).", null=True)),
                ('immagine', models.ImageField(blank=True, help_text="Immagine rappresentativa dell'evento.", null=True, upload_to='eventi/')),
                ('is_active', models.BooleanField(default=True, help_text="Se l'evento è attivo e visibile.")),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventi',
                'ordering': ['-data_inizio'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Notizia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('data_pubblicazione', models.DateTimeField(auto_now_add=True)),
                ('immagine', models.ImageField(blank=True, help_text='Immagine principale della notizia.', null=True, upload_to='notizie/')),
                ('is_active', models.BooleanField(default=True, help_text='Se la notizia è attiva e visibile.')),
            ],
            options={
                'verbose_name': 'Notizia',
                'verbose_name_plural': 'Notizie',
                'ordering': ['-data_pubblicazione'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Opera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('anno_pubblicazione', models.IntegerField(blank=True, null=True)),
                ('link_wikisource', models.URLField(help_text="Link alla pagina dell'opera su Wikisource.", max_length=500)),
                ('copertina', models.ImageField(blank=True, help_text="Carica la copertina dell'opera.", null=True, upload_to='copertine_opere/')),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opere', to='parco_verismo.autore')),
            ],
            options={
                'ordering': ['translations__titolo'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EventoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField(help_text="Descrizione dettagliata dell'evento.")),
                ('luogo', models.CharField(help_text="Luogo dove si svolge l'evento.", max_length=200)),
                ('indirizzo', models.TextField(blank=True, help_text='Indirizzo completo del luogo.', null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='parco_verismo.evento')),
            ],
            options={
                'verbose_name': 'Evento Translation',
                'db_table': 'parco_verismo_evento_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NotiziaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('titolo', models.CharField(max_length=200)),
                ('contenuto', models.TextField(help_text='Contenuto completo della notizia.')),
                ('riassunto', models.TextField(blank=True, help_text='Riassunto breve per le liste (opzionale).', null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='parco_verismo.notizia')),
            ],
            options={
                'verbose_name': 'Notizia Translation',
                'db_table': 'parco_verismo_notizia_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OperaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('titolo', models.CharField(max_length=200)),
                ('trama', models.TextField(help_text="Breve trama o descrizione dell'opera.")),
                ('analisi', models.TextField(blank=True, help_text='Spunti di analisi o contesto storico.', null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='parco_verismo.opera')),
            ],
            options={
                'verbose_name': 'opera Translation',
                'db_table': 'parco_verismo_opera_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
