# Generated by Django 5.2.8 on 2025-11-16 02:51

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('data_pubblicazione', models.DateTimeField(auto_now_add=True)),
                ('anno_pubblicazione', models.IntegerField(blank=True, help_text='Anno di pubblicazione del documento/studio.', null=True)),
                ('pdf_file', models.FileField(help_text='File PDF del documento o studio.', upload_to='documenti/')),
                ('anteprima', models.ImageField(blank=True, help_text='Immagine di anteprima del documento (copertina o prima pagina).', null=True, upload_to='documenti/anteprime/')),
                ('is_active', models.BooleanField(default=True, help_text='Se il documento è attivo e visibile.')),
                ('tipo', models.CharField(choices=[('documento', 'Documento'), ('studio', 'Studio'), ('ricerca', 'Ricerca'), ('saggio', 'Saggio')], default='documento', help_text='Tipo di documento/studio.', max_length=50)),
                ('autori', models.CharField(blank=True, help_text="Autori del documento/studio (es: 'Mario Rossi, Luigi Bianchi').", max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documenti e Studi',
                'ordering': ['-data_pubblicazione'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='autore',
            options={'verbose_name': 'Autore', 'verbose_name_plural': 'Autori'},
        ),
        migrations.AlterModelOptions(
            name='opera',
            options={'ordering': ['translations__titolo'], 'verbose_name': 'Opera', 'verbose_name_plural': 'Opere'},
        ),
        migrations.AlterModelOptions(
            name='operatranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Opera Translation'},
        ),
        migrations.CreateModel(
            name='DocumentoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('titolo', models.CharField(help_text='Titolo del documento o studio.', max_length=200)),
                ('descrizione', models.TextField(help_text='Descrizione dettagliata del contenuto del documento.')),
                ('riassunto', models.TextField(blank=True, help_text='Riassunto breve per le liste (opzionale).', null=True)),
                ('parole_chiave', models.CharField(blank=True, help_text='Parole chiave separate da virgola (opzionale).', max_length=300, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='parco_verismo.documento')),
            ],
            options={
                'verbose_name': 'Documento Translation',
                'db_table': 'parco_verismo_documento_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
