# Generated by Django 5.2.8 on 2025-11-16 02:59

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0002_documento_alter_autore_options_alter_opera_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoArchivio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(help_text="Carica la foto per l'archivio.", upload_to='archivio_fotografico/')),
                ('data_aggiunta', models.DateTimeField(auto_now_add=True)),
                ('ordine', models.IntegerField(default=0, help_text='Ordine di visualizzazione (numero più basso = prima).')),
                ('is_active', models.BooleanField(default=True, help_text='Se la foto è attiva e visibile.')),
                ('categoria', models.CharField(blank=True, help_text="Categoria della foto (es: 'Luoghi', 'Eventi', 'Personaggi').", max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Foto Archivio',
                'verbose_name_plural': 'Archivio Fotografico',
                'ordering': ['ordine', '-data_aggiunta'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FotoArchivioTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('titolo', models.CharField(blank=True, help_text='Titolo della foto (opzionale).', max_length=200, null=True)),
                ('descrizione', models.TextField(blank=True, help_text='Descrizione della foto (opzionale).', null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='parco_verismo.fotoarchivio')),
            ],
            options={
                'verbose_name': 'Foto Archivio Translation',
                'db_table': 'parco_verismo_fotoarchivio_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
