# Generated by Django 5.2.8 on 2025-12-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parco_verismo", "0003_fotoarchivio_autore"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prenotazione",
            options={
                "ordering": ["-data_richiesta"],
                "verbose_name": "Richiesta di contatto",
                "verbose_name_plural": "Richieste di contatto",
            },
        ),
        migrations.AddField(
            model_name="prenotazione",
            name="ente",
            field=models.CharField(
                blank=True,
                help_text="Facoltativo",
                max_length=200,
                verbose_name="Ente / Istituzione",
            ),
        ),
        migrations.AddField(
            model_name="prenotazione",
            name="oggetto",
            field=models.CharField(
                blank=True,
                help_text="Oggetto della richiesta (facoltativo)",
                max_length=200,
                verbose_name="Oggetto",
            ),
        ),
    ]
