# Generated by Django 5.2.8 on 2025-12-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0003_fotoarchivio_autore'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatranslation',
            name='breve_descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Breve descrizione'),
        ),
        migrations.AlterField(
            model_name='opera',
            name='anno_pubblicazione',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anno di pubblicazione'),
        ),
        migrations.AlterField(
            model_name='opera',
            name='copertina',
            field=models.ImageField(blank=True, help_text="Carica la copertina dell'opera.", null=True, upload_to='copertine/'),
        ),
        migrations.AlterField(
            model_name='operatranslation',
            name='analisi',
            field=models.TextField(blank=True, help_text='Spunti di analisi o contesto storico.', null=True, verbose_name='Analisi e contesto'),
        ),
        migrations.AlterField(
            model_name='operatranslation',
            name='trama',
            field=models.TextField(help_text="Breve trama o descrizione dell'opera.", verbose_name='Trama'),
        ),
    ]
