# Generated by Django 5.2.8 on 2025-12-20 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parco_verismo", "0004_alter_prenotazione_options_prenotazione_ente_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Prenotazione",
            new_name="Richiesta",
        ),
    ]
