# Generated by Django 5.2.8 on 2025-12-23 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0004_operatranslation_breve_descrizione_and_more'),
        ('parco_verismo', '0007_make_oggetto_messaggio_required'),
    ]

    operations = [
    ]
