# Generated by Django 5.2.8 on 2025-12-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0009_auto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autore',
            name='slug',
            field=models.SlugField(blank=True, help_text='Lascia vuoto per generare automaticamente dal nome.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='slug',
            field=models.SlugField(blank=True, help_text='Lascia vuoto per generare automaticamente dal titolo.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='slug',
            field=models.SlugField(blank=True, help_text='Lascia vuoto per generare automaticamente dal titolo.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='opera',
            name='slug',
            field=models.SlugField(blank=True, help_text='Lascia vuoto per generare automaticamente dal titolo.', max_length=200, unique=True),
        ),
    ]
