# Generated by Django 5.2.8 on 2025-12-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0011_itinerario_colore_percorso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerario',
            options={'ordering': ['ordine', 'slug'], 'verbose_name': 'Itinerario', 'verbose_name_plural': 'Itinerari'},
        ),
        migrations.AlterModelOptions(
            name='opera',
            options={'ordering': ['anno_pubblicazione', 'slug'], 'verbose_name': 'Opera', 'verbose_name_plural': 'Opere'},
        ),
    ]
