# Generated by Django 5.2.8 on 2026-02-03 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0017_remove_itinerario_icona_percorso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerario',
            name='tipo',
            field=models.CharField(choices=[('verghiano', 'Itinerario Verghiano'), ('capuaniano', 'Itinerario Capuaniano'), ('tematico', 'Cammino del Verismo')], default='verghiano', help_text='Tipo di itinerario letterario.', max_length=50),
        ),
        migrations.AlterField(
            model_name='notizia',
            name='data_pubblicazione',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
