# Generated by Django 5.2.8 on 2026-02-14 00:13

import autoslug.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0021_luogoletterario_operainluogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ristorante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Ristorante')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ristoranti/loghi/', verbose_name='Logo/Icona')),
                ('indirizzo', models.CharField(max_length=255, verbose_name='Indirizzo')),
                ('numeri', models.CharField(max_length=100, verbose_name='Numeri di telefono')),
                ('menu', models.ImageField(upload_to='ristoranti/menu/', verbose_name='Menu (Immagine)')),
            ],
            options={
                'verbose_name': 'Ristorante',
                'verbose_name_plural': 'Ristoranti',
                'ordering': ['nome'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
    ]
