# Generated by Django 5.2.8 on 2026-02-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0022_ristorante'),
    ]

    operations = [
        migrations.AddField(
            model_name='ristorante',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo di Ristorante'),
        ),
    ]
