# Generated by Django 5.2.8 on 2026-02-14 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0023_ristorante_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ristorante',
            name='luogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parco_verismo.luogoletterario', verbose_name='Luogo'),
        ),
    ]
