# Generated by Django 5.2.8 on 2026-02-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0024_ristorante_luogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ristorante',
            name='link_maps',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Google Maps'),
        ),
    ]
