# Generated by Django 5.2.8 on 2026-02-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0025_ristorante_link_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ristorante',
            name='luogo',
            field=models.CharField(blank=True, choices=[('mineo', 'Mineo'), ('licodia-eubea', 'Licodia Eubea'), ('vizzini', 'Vizzini')], default='', max_length=20, verbose_name='Luogo'),
        ),
    ]
