# Generated by Django 5.2.8 on 2026-02-15 05:04

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parco_verismo', '0026_alter_ristorante_luogo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ristorante',
            options={'verbose_name': 'Ristorante', 'verbose_name_plural': 'Ristoranti'},
        ),
        migrations.RemoveField(
            model_name='ristorante',
            name='indirizzo',
        ),
        migrations.RemoveField(
            model_name='ristorante',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='ristorante',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='ristorante',
            name='slug',
            field=models.SlugField(blank=True, help_text='Lascia vuoto per generare automaticamente dal nome.', max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.CreateModel(
            name='RistoranteTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Ristorante')),
                ('tipo', models.CharField(blank=True, max_length=100, verbose_name='Tipo di Ristorante')),
                ('indirizzo', models.CharField(max_length=255, verbose_name='Indirizzo')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='parco_verismo.ristorante')),
            ],
            options={
                'verbose_name': 'Ristorante Translation',
                'db_table': 'parco_verismo_ristorante_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
